version: "3.8"
services:
  db:
    image: postgres:12.0-alpine
    env_file: 
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./server
    command: >
      sh -c "python server/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db

volumes:
  postgres_data: