version: "3.8"
services:
  web:
    build: ./server
    command: python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env