version: "3.8"
services:
  db:
    image: postgres:12.0-alpine
    env_file: 
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./server
    command: >
      sh -c "python server/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db
  frontend:
    stdin_open: true
    build: ./client
    volumes:
      - ./client:/usr/src/frontend
      - node-modules:/usr/src/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  node-modules: