# Generated by Django 3.1.2 on 2020-10-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coursemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='students',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='courses',
            field=models.ManyToManyField(to='api.CourseModel'),
        ),
    ]
