# Generated by Django 3.1.2 on 2020-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201111_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='courses',
            field=models.ManyToManyField(to='api.CourseModel'),
        ),
    ]
