# Generated by Django 3.1.2 on 2020-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201111_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='courses',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='teachers',
            field=models.ManyToManyField(to='api.TeacherModel'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='courses',
            field=models.ManyToManyField(to='api.CourseModel'),
        ),
    ]
